baseURL = "http://example.org/"
languageCode = "en-us"
title = "Rock Mechanics"

	
[menu]
	[[menu.main]]
		identifier = "item-1"
		name = "Rock as Geo-Material"
		url = "item-1"
		weight = "1"
	[[menu.main]]
		identifier = "item-1-a"
		name = "Introduction"
		url = "/docs/introduction"
		parent = "item-1"
		weight = "1"
	[[menu.main]]
		identifier = "item-1-b"
		name = "Rock as Natural Material"
		url = "#"
		parent = "item-1"
		weight = "2"
	[[menu.main]]
		identifier = "item-2"
		name = "Weight-Volume Relationships of Porous Material"
		url = "item-2"
		weight = "2"
	[[menu.main]]
		identifier = "item-2-a"
		name = "Sample Link 1"
		url = "#"
		parent = "item-2"
		weight = "1"
	[[menu.main]]
		identifier = "item-2-b"
		name = "Sample Link 2"
		url = "#"
		parent = "item-2"
		weight = "2"