baseURL = "http://example.org/"
languageCode = "en-us"
title = "Rock Mechanics"

	
[menu]
	[[menu.main]]
		identifier = "item-1"
		name = "Rock as Geo-Material"
		url = "/docs/rock-as-geo-material/"
		post = "fas fa-caret-down"
		weight = "1"
	[[menu.main]]
		identifier = "item-1-a"
		name = "Introduction"
		url = "/docs/rock-as-geo-material/introduction/"
		parent = "item-1"
		weight = "1"
	[[menu.main]]
		identifier = "item-1-b"
		name = "Rock as Natural Material"
		url = "/docs/rock-as-geo-material/rock-as-natural-material/"
		parent = "item-1"
		weight = "2"
	[[menu.main]]
		identifier = "item-1-c"
		name = "Intact Rock v/s Rock Mass"
		url = "/docs/rock-as-geo-material/intact-rock-versus-rock-mass/"
		parent = "item-1"
		weight = "3"
	[[menu.main]]
		identifier = "item-2"
		name = "Weight-Volume Relationship of Porous Material"
		url = "/docs/weight-volume-relationship-of-porous-material/"
		post = "fas fa-caret-down"
		weight = "2"
	[[menu.main]]
		identifier = "item-2-a"
		name = "Introduction"
		url = "/docs/weight-volume-relationship-of-porous-material/introduction/"
		parent = "item-2"
		weight = "1"
	[[menu.main]]
		identifier = "item-2-b"
		name = "Phase Diagram"
		url = "/docs/weight-volume-relationship-of-porous-material/phase-diagram/"
		parent = "item-2"
		weight = "2"
	[[menu.main]]
		identifier = "item-2-c"
		name = "Weight Volume Relationships"
		url = "/docs/weight-volume-relationship-of-porous-material/weight-volume-relationships/"
		parent = "item-2"
		weight = "3"
	[[menu.main]]
		identifier = "item-3"
		name = "Rock Mass Classification Systems"
		url = "/docs/rock-mass-classification-systems/"
		post = "fas fa-caret-down"
		weight = "3"
	[[menu.main]]
		identifier = "item-3-a"
		name = "Definition & Properties of Rock Mass"
		url = "/docs/rock-mass-classification-systems/definition-and-properties-of-rock-mass/"
		parent = "item-3"
		weight = "1"
